apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "name": "prometheus",
                "type": "prometheus",
                "editable": false,
                "orgId": 1,
                "version": 1,
                "url": "http://prometheus:9090",
                "access": "proxy",
            }
        ]
    }

