apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: production-deployer
rules:
  - apiGroups: ["apps","extensions", "autoscaling", "batch", ""]
    resources: ["deployments","configmaps","pods", "ingresses", "services", "horizontalpodautoscalers", "cronjobs"]
    verbs: ["create","get","delete","list","update","edit","watch","exec","patch"]

  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "servicemonitors"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: production-deployer
roleRef:
  kind: ClusterRole
  name: production-deployer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: system:codebuild:production-deployer # matches terraform/kubernetes-cluster/aws_auth.tf
    apiGroup: rbac.authorization.k8s.io

