apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    team: DPT
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - monitoring
