kind: Service
apiVersion: v1
metadata:
  name: traefik-admin-service
  namespace: traefik
  labels:
    app: traefik
    admin: "true"
spec:
  selector:
    app: traefik
    service: traefik
  ports:
    - protocol: TCP
      port: 8080
      name: admin
