apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    team: DPT
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - monitoring
